language: java
# how to install and set jdk on travis:
# - Testing Against Multiple JDKs
#   https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
# - JVM images
#   https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images
# - Customizing the Build / Build Matrix
#   https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - oraclejdk8

before_install:
  # workaroud for "buffer overflow detected" problem of openjdk:
  #     https://github.com/travis-ci/travis-ci/issues/5227
  # borrow from https://github.com/miguno/kafka-storm-starter/blob/01dd534263eb867304c06cd2a72f640da1bd9367/.travis.yml
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

  # https://docs.travis-ci.com/user/languages/java/#Using-Java-10-and-later
  # https://github.com/sormuras/bach/blob/master/install-jdk.sh
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x install-jdk.sh

  # output env info
  - ls -l /usr/lib/jvm && ls /usr/lib/jvm/*
  - echo -e "JAVA_HOME=$JAVA_HOME\nPATH=$PATH"
  - ./mvnw --version

install:
  - pip install --user codecov

script:
  # default oracle jdk 8, do build and test
  - ./mvnw clean install --batch-mode
  - ./scritps/run-agent-test.sh
  # open jdk 6
  - jdk_switcher use openjdk6
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  # open jdk 7
  - jdk_switcher use openjdk7
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  # open jdk 8
  - jdk_switcher use openjdk8
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  # oracle jdk 9
  - jdk_switcher use oraclejdk9
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  # open jdk 9
  - export JAVA_HOME=$HOME/.jdk/openjdk9
  - if [ ! -d "$JAVA_HOME" ]; then ./install-jdk.sh --feature 9 --os linux-x64 --license GPL --target $JAVA_HOME; fi
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  #  oracle jdk 10
  - export JAVA_HOME=$HOME/.jdk/oraclejdk10
  - if [ ! -d "$JAVA_HOME" ]; then ./install-jdk.sh --feature 10 --os linux-x64 --license BCL --target $JAVA_HOME; fi
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  #  open jdk 10
  - export JAVA_HOME=$HOME/.jdk/openjdk10
  - if [ ! -d "$JAVA_HOME" ]; then ./install-jdk.sh --feature 10 --os linux-x64 --license GPL --target $JAVA_HOME; fi
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  #  open jdk 11
  - export JAVA_HOME=$HOME/.jdk/openjdk11
  - if [ ! -d "$JAVA_HOME" ]; then ./install-jdk.sh --feature 11 --os linux-x64 --license GPL --target $JAVA_HOME; fi
  - ./scritps/run-junit.sh skipClean
  - ./scritps/run-agent-test.sh skipClean
  # codecov
  - jdk_switcher use oraclejdk8
  - mvn clean -V
  - mvn cobertura:cobertura

after_success:
  - codecov

# Caching Dependencies and Directories
# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.jdk
    - $HOME/.cache/pip
before_cache:
  # clear TTL maven self install
  - rm -rf $HOME/.m2/repository/com/alibaba/transmittable-thread-local